### ISSUE TITLE
win10 64出现错误

### ISSUE THREAD

**Issue by wclmgcd** [oluceps/clash2sing-box#32]
clash2sing-box 0.2.0
使用clash2sing-box-x86_64-windows.exe --path  config.yaml -g -f -o config.json，提示
thread 'main' panicked at 'not yet implemented', src\main.rs:238:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by oluceps** [comment]
`config.yaml`文件内的节点包含哪些协议呢

**Comment by wclmgcd** [comment]
ss,http,vless,vmess

**Comment by oluceps** [comment]
> ss,http,vless,vmess

暂时还不支持vless的转换，详情可以看README界面。等有空了我顺便写一下vless的支持。  
可以先把vless的节点注释掉再试试能不能正常转换

**Comment by wclmgcd** [comment]
感谢大佬，已成功
