### ISSUE TITLE
paradigm.rs 可以自定义吗

### ISSUE THREAD

**Issue by yuumimi** [oluceps/clash2sing-box#58]
因为有自己的规则，fork 后修改 paradigm.rs 编译失败，能否指定规则文件呢？

**Comment by oluceps** [comment]
可以自定义。在你的fork上我编译和使用是没问题的， CI fail 是因为最后上传的步骤没有仓库访问权限。

**Comment by yuumimi** [comment]
如果能指定 sing-box 的 config.json 源文件的话就方便多了。

**Comment by oluceps** [comment]
> 如果能指定 sing-box 的 config.json 源文件的话就方便多了。

之后有计划添加一个「更新」的选项，指定config.json 然后把 parse 出来的节点信息附加进去。

**Comment by lauren12133** [comment]
> 可以自定义。在你的fork上我编译和使用是没问题的， CI fail 是因为最后上传的步骤没有仓库访问权限。

 CI fail 是因为最后上传的步骤没有仓库访问权限。 有解决方法吗 尝试自己加入token也过不了上传那部 也是config.json自定义需求
