### ISSUE TITLE
[BUG] Demo 站挂了

### ISSUE THREAD

**Issue by 117503445** [oluceps/clash2sing-box#67]
2024.1.9 16:30, demo 站 <https://ctos.magicb.uk/> 挂了

**Comment by oluceps** [comment]
Fixed.

**Comment by adoyle-h** [comment]
无法访问网站

**Comment by oluceps** [comment]
> 无法访问网站

Fixed. New Demo Site -> <https://oluceps.github.io/clash2sing-box/>
